name: toikhoe
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:

  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_zalo: ^0.0.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.1
  mysql1: ^0.20.0
  riverpod_annotation: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/
